export enum PermissionEnum {
  // User Management
  USER_CREATE = 'USER_CREATE',
  USER_READ_ALL = 'USER_READ_ALL',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_MANAGE_ROLES = 'USER_MANAGE_ROLES',

  // Product Management
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_READ = 'PRODUCT_READ',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',

  // Customer Management
  CUSTOMER_CREATE = 'CUSTOMER_CREATE',
  CUSTOMER_READ_ALL = 'CUSTOMER_READ_ALL',
  CUSTOMER_READ_OWN = 'CUSTOMER_READ_OWN',
  CUSTOMER_UPDATE = 'CUSTOMER_UPDATE',

  // Order Management
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_READ_ALL = 'ORDER_READ_ALL',
  ORDER_READ_OWN = 'ORDER_READ_OWN',
  ORDER_UPDATE_STATUS = 'ORDER_UPDATE_STATUS',
  ORDER_CANCEL = 'ORDER_CANCEL',

  // Route Management
  ROUTE_CREATE = 'ROUTE_CREATE',
  ROUTE_READ_ALL = 'ROUTE_READ_ALL',
  ROUTE_READ_OWN = 'ROUTE_READ_OWN',
  ROUTE_UPDATE_STATUS = 'ROUTE_UPDATE_STATUS',

  // Report Management
  REPORT_READ_ALL = 'REPORT_READ_ALL',
  REPORT_READ_OWN = 'REPORT_READ_OWN',

  // Notification Management
  NOTIFICATION_READ = 'NOTIFICATION_READ',
}
